### ISSUE TITLE
exercise 4

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/MySQL#3]
Exercise 4: Back up and restoreTake back up of the db you created for practice/exercise and send it to me.Now create a new database named "restored" and restore that backup into this DB.

https://github.com/wilsonokibe/MySQL/tree/master/exercise4

**Comment by segunadeleye** [comment]
https://github.com/wilsonokibe/MySQL/blob/master/exercise4/exercise4.sql#L3
https://github.com/wilsonokibe/MySQL/blob/master/exercise4/exercise4.sql#L7
Do we really need `-h localhost`?

**Comment by wilsonokibe** [comment]
we do not necessarily have to specify -h localhost when we are working on the local host, because system automatically assigns -h localhost as default.
However, it is compulsory to specify other servers in case we are not using localhost

**Comment by segunadeleye** [comment]
Okay cool
