### ISSUE TITLE
exercise -practice

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/MySQL#4]
Exercise: Alter TableCreate a table named "testing_table" with following fields:
name (string)contact_name (string)roll_no (string)Now:Delete column name, rename contact_name to username. Add two fields first_name, last_name. Also change the type of roll_no to integer

https://github.com/wilsonokibe/MySQL/blob/master/Exercise-AlterTable.sql

**Comment by segunadeleye** [comment]
Good
